Feature/add comment
TheDevengers/welldone-BE pull request #15
Opened 2019-09-22 14:49 UTC by SabrinaFZ

* Creación de la nueva vista CommentsView
* Añadir nuevo endpoint /comments/slug
* Modificar plantilla HTML para incluir el formulario de creacion nuevo comentario
* Creación formulario CommentForm
* Creación nuevo controlador CommentController

2019-09-22 17:35 UTC, hvctgr approved these changes

2019-09-22 21:59 UTC, basanta79 approved these changes

2019-09-23 10:51 UTC, Ferveloper requested changes

2019-09-23 10:51 UTC, Ferveloper commented on changelog.md
> +
Tus comentarios en el readme los has puesto antes de un último párrafo mio de una HU anterior. Edítalo para que no parezca que son comentarios de tu HU

2019-09-23 12:51 UTC, SabrinaFZ commented on changelog.md
> +
Ok, ahora lo hago!

2019-09-23 17:17 UTC, Vegekku approved these changes

2019-09-23 17:33 UTC, merged