Feature/search articles
TheDevengers/welldone-BE pull request #18
Opened 2019-09-22 21:40 UTC by Ferveloper

Notas:
* Modificado el controller `articles.py` para filtrar articulos por búsqueda si la URL incluye el parámetro `search`, el cual se genera al realizar el usar el buscador del header. Se busca en los campos `title`, `ìntroduction` y `body`, y se limitan los resultados a máximo 20 artículos por defecto.
* Modificado la plantilla `list.html`para mostrar un mensaje de que no se encuentran resultados de búsqueda en caso de que el objeto `articles_list` tenga 0 elementos.

La búsqueda es case insensitive, pero busca las palabras con acentos, lo cual no es muy bueno de cara a la UX. Incluiré en Trello una HU opcional para mejorar la búsqueda, quizás usando el operador __iregex.
https://docs.djangoproject.com/en/2.2/ref/models/querysets/#iregex

2019-09-22 21:52 UTC, SabrinaFZ commented on articles/controllers/articles.py
> +        search = request.GET.get('search') if request.GET.get('search') else ''
Una cosilla, y si en el buscador escribes un espacio como lo trata? también te lo busca?

2019-09-23 10:27 UTC, Ferveloper commented on articles/controllers/articles.py
> +        search = request.GET.get('search') if request.GET.get('search') else ''
Tal como está implementado, me imagino que hará la búsqueda de espacios. Habría que ver si se puede aplicar un método tipo trim para eliminar espacios innecesarios.

2019-09-23 10:59 UTC, hvctgr approved these changes

2019-09-23 17:32 UTC, Vegekku commented on articles/templates/articles/list.html
>                  Page {{ article_list.number }} of {{ latest_articles.paginator.num_pages }}
El fallo es mio jejeje Cambis `latest_articles` por `article_list`

2019-09-23 17:44 UTC, Vegekku reviewed
Mantendría el termino de búsqueda en el campo de búsqueda del header

2019-09-23 18:03 UTC, Vegekku requested changes

2019-09-23 18:03 UTC, Vegekku commented on articles/controllers/articles.py
> +        search = request.GET.get('search') if request.GET.get('search') else ''
Creo que puede simplificarse con `request.GET.get('search','')`

2019-09-23 18:03 UTC, Vegekku commented on articles/controllers/articles.py
> +            .all()[:SEARCH_RESULTS] if request.GET.get('search') else article_list
Creo que SEARCH_RESULTS no debe ir aquí. Aquí limitamos los resultados devueltos por el modelo a 20, si lo ponemos en `Paginator(article_list, SEARCH_RESULTS) limitamos los resultados devueltos a la vista. Es decir podemos tener 40 coincidencias en el modelo, y en la primera página de la vista mostrar 20.

2019-09-23 18:03 UTC, Vegekku commented on articles/controllers/articles.py
>          paginator = Paginator(article_list, shown)
Si decides hacer lo de la paginación, tendrás que condicionar al listado que se te mostrando (normal o búsqueda)

2019-09-23 18:03 UTC, Vegekku commented on articles/controllers/articles.py
> +            .all()[:SEARCH_RESULTS] if request.GET.get('search') else article_list
Como el valor de `request.GET.get('search')` ya lo asignaste al principio a `search`, yo usaría `search` como condición. Reduces el acceso a request una única vez, y si tienes cambiar algo, lo haces en una línea

2019-09-23 18:03 UTC, Vegekku commented on articles/controllers/articles.py
>          shown_param = '&shown={0}'.format(shown) if shown != DEFAULT_SHOWN else ''
Ahora mismo la paginación se rompe en la búsqueda porque al 'pasar página' no se mantiene el parámetro `search` en la query. Tendrás que hacer algo similar pero para `search`. Trataría de que al template llegue una única variable `show_param` compuesta por `shown` y `search`, si es el caso

2019-09-23 19:13 UTC, Ferveloper commented on articles/templates/articles/list.html
>                  Page {{ article_list.number }} of {{ latest_articles.paginator.num_pages }}
Ah vale, veia un fallo en el tema del paginado, pero no habia entrado a revisar el motivo. Lo cambio

2019-09-23 19:14 UTC, Ferveloper commented on articles/controllers/articles.py
> +        search = request.GET.get('search') if request.GET.get('search') else ''
Ok, no recordaba esa posibilidad, Gracias.

2019-09-23 19:17 UTC, Ferveloper commented
> Mantendría el termino de búsqueda en el campo de búsqueda del header

Sí, estoy de acuerdo, aunque de momento estaba dejando el código del campo de búsqueda como me lo había encontrado. Pero creo que lo voy a cambiar.

2019-09-23 19:34 UTC, Ferveloper commented on articles/controllers/articles.py
> +            .all()[:SEARCH_RESULTS] if request.GET.get('search') else article_list
> Creo que SEARCH_RESULTS no debe ir aquí. Aquí limitamos los resultados devueltos por el modelo a 20, si lo ponemos en `Paginator(article_list, SEARCH_RESULTS) limitamos los resultados devueltos a la vista. Es decir podemos tener 40 coincidencias en el modelo, y en la primera página de la vista mostrar 20.

Utilizo el concepto de SEARCH_RESULTS de forma diferente y complementaria a DEFAULT_SHOWN, de acuerdo a lo ya implementado y mi interpretación de la HU.
DEFAULT_SHOWN determina los resultados por página, mientras que SEARCH_RESULTS determina los resultados totales a mostrar (es requisito de la HU no mostrar todas las coincidencias posibles de la búsqueda, sino un número limitado del total, que he decidido que sea máximo 20).
Como por defecto hemos puesto 10 artículos por página, he decidido poner un máximo de 20 artículos, para dejar los resultados de búsqueda en dos páginas. máximo. Por tanto, SEARCH_RESULTS no debería ir como argumento de Paginator según entiendo la HU.

2019-09-23 19:38 UTC, Ferveloper commented on articles/controllers/articles.py
> +            .all()[:SEARCH_RESULTS] if request.GET.get('search') else article_list
> Como el valor de `request.GET.get('search')` ya lo asignaste al principio a `search`, yo usaría `search` como condición. Reduces el acceso a request una única vez, y si tienes cambiar algo, lo haces en una línea

Ok, cierto, no había caído en que una cadena vacía se evalúa como `False`, pensaba que tenía que volver a evaluar si el parámetro `search`existe en la query.

2019-09-23 19:40 UTC, Ferveloper commented on articles/controllers/articles.py
>          paginator = Paginator(article_list, shown)
Esa frase no me ha quedado muy clara 😅

2019-09-23 19:56 UTC, Ferveloper commented on articles/controllers/articles.py
>          shown_param = '&shown={0}'.format(shown) if shown != DEFAULT_SHOWN else ''
Ok, voy a resolver eso

2019-09-24 17:35 UTC, Vegekku commented on articles/controllers/articles.py
>          paginator = Paginator(article_list, shown)
ni yo la redacté muy bien jajaja era que si al final no limitabas la query a 20, sino la paginación a 20, `shown` debía cambiar según el listado mostrado (normal o búsqueda). Ya da igual por el razonamiento que me has dado :D

2019-09-24 17:38 UTC, Vegekku approved these changes

2019-09-24 17:38 UTC, Vegekku commented on articles/controllers/articles.py
>          paginator = Paginator(article_list, shown)
ni yo la redacté muy bien jajaja era que si al final no limitabas la query a 20, sino la paginación a 20, shown debía cambiar según el listado mostrado (normal o búsqueda). Ya da igual por el razonamiento que me has dado :D

2019-09-24 18:09 UTC, Ferveloper commented on articles/controllers/articles.py
> +        search = request.GET.get('search') if request.GET.get('search') else ''
Lo he mirado un poco y he añadido el método `strip()` al string recibido del `request.GET('search')`. Eso asegura eliminar espacios innecesarios al principio y al final, pero he comprobado que si mandas solo espacios desde la web se lanza una búsqueda, porque cada espacio se trata como un término de búsqueda. No es nada grave, pero se podría trabajar en corregir ese detalle desde front con JS para no llegar a lanzar un GET de sólo espacios. En back, si se recibe una petición de un cliente desconocido con sólo espacios, se le enviarán 20 resultados que coincidan, eso en sí no sería un error. Respecto a lo de front, sí se podría optimizar y se puede poner como una HU opcional.

2019-09-25 05:43 UTC, SabrinaFZ approved these changes

2019-09-25 10:57 UTC, hvctgr approved these changes

2019-09-25 19:29 UTC, merged