Feature/api rest
TheDevengers/welldone-BE pull request #2
Opened 2019-09-10 17:29 UTC by Vegekku

2019-09-11 12:01 UTC, SabrinaFZ reviewed
¿Por qué el def post en ArticlesAPI esta en una clase distinta a get, put y delete? Es sólo por saber

2019-09-11 17:34 UTC, Vegekku commented
> ¿Por qué el def post en ArticlesAPI esta en una clase distinta a get, put y delete? Es sólo por saber

Lo saque de mi práctica. ArticlesAPI es para el conjunto de artículos, mientras que ArticleAPI son para interacciones con un artículo (por eso llevan el parametro pk, primary key).
Esto puede acabar cambiando, pues va a depender de como y quien lo desarrolle, por eso solo están las declaraciones

2019-09-11 20:32 UTC, Ferveloper requested changes

2019-09-11 20:32 UTC, Ferveloper commented on main/urls.py
> +    path('{0}/articles/<int:pk>/favorite'.format(api_path), view, name='article_favorite_api'),
Los favoritos no cuelgan de article, sino de user. Es un usuario el que tiene una lista de articulos favoritos. Se debería hacer GET a /users/\<int:pk\>/favorites y se devolverían las pk de los artículos favoritos del usuario con la pk enviada en la URL.

2019-09-11 20:32 UTC, Ferveloper commented on main/urls.py
> +    path('{0}/articles/<int:pk>/highlight'.format(api_path), view, name='article_highlights_api'),
Creo que por convenio es mejor que todo sea en plural, en este caso highlights, y acabado en / para los listados, es decir, highlights/

2019-09-11 20:32 UTC, Ferveloper commented on main/urls.py
> +    path('{0}/articles/<int:pk>/highlight/<int:pk>'.format(api_path), view, name='article_highlight_api'),
En principio creo que este endpoint no es necesario, ya que al renderizar un articulo necesitamos recibir del API el array de textos a resaltar, y sobre el que iteraremos, pero pedir un highlight concreto por su pk no le veo necesidad.

2019-09-11 20:32 UTC, Ferveloper commented on main/urls.py
> +    path('{0}/articles/<int:pk>/mention'.format(api_path), view, name='article_mention_api'),
Para solicitar el listado de menciones, mejor por convenio acabar en plural y /, es decir, mentions/

2019-09-11 20:32 UTC, Ferveloper commented on main/urls.py
> +    path('{0}/articles'.format(api_path), ArticlesAPI.as_view(), name='articles_api'),
Acabar las URLs de listados con /

2019-09-11 20:32 UTC, Ferveloper commented on main/urls.py
> +    path('{0}/users/<int:pk>/follow'.format(api_path), view, name='user_follow_api'),
Si este endpoint es para decir que el user X sigue al user Y, deberian ser dos pk. /users/\<int:pk\>/follow/\<int:pk\>

2019-09-11 20:32 UTC, Ferveloper commented on main/urls.py
> +    path('{0}/users/<int:pk>/unfollow'.format(api_path), view, name='user_unfollow_api'),
Si este endpoint es para decir que el user X deja de seguir al user Y, deberian ser dos pk. /users/\<int:pk\>/unfollow/\<int:pk\>

2019-09-11 20:32 UTC, Ferveloper commented on main/urls.py
> +    path('{0}/users'.format(api_path), UsersAPI.as_view(), name='users_api'),
Acabar las URLs de listados con /

2019-09-11 20:32 UTC, Ferveloper commented on main/urls.py
> +    # API
Si no me equivoco, falta el endpoint /users/\<int:pk\>/followers/ para obtener todos los seguidores y seguidos de un usuario. También /users/\<int:pk\>/highlights/ para obtener los subrayados de un usuario para la webapp, lo mismo que se ha hecho para articulos para la web.

2019-09-12 09:47 UTC, Vegekku commented on main/urls.py
> +    path('{0}/articles/<int:pk>/favorite'.format(api_path), view, name='article_favorite_api'),
Este endpoint no sería para GET, sino para POST. Al llamar a este endpoint con el usuario logueado, se vincula el artículo al usuario.

Para obtener el listado de artículos favoritos yo lo planteo llamando a /articles con los parámetros _ordering=-modification_date;limit=10;page=1;**favorite=username**_

2019-09-12 09:47 UTC, Vegekku commented on main/urls.py
> +    path('{0}/articles/<int:pk>/highlight/<int:pk>'.format(api_path), view, name='article_highlight_api'),
En este caso no sería GET, sino DELETE. Con este endpoint borramos un resaltado concreto

2019-09-12 09:47 UTC, Vegekku commented on main/urls.py
> +    path('{0}/articles/<int:pk>/highlight'.format(api_path), view, name='article_highlights_api'),
Este endpoint vale tanto para GET como POST. Yo en la práctica dejé todas las urls y endpoints sin acabar en '/', no recuerdo porque era necesario ponérselo.

2019-09-12 09:47 UTC, Vegekku commented on main/urls.py
> +    path('{0}/articles/<int:pk>/mention'.format(api_path), view, name='article_mention_api'),
Como el anterior, este valdría tanto para GET como POST, aunque no creo que lleguemos a usarlo con GET

2019-09-12 09:47 UTC, Vegekku commented on main/urls.py
> +    path('{0}/users/<int:pk>/follow'.format(api_path), view, name='user_follow_api'),
Es para decir que sigo al usuario del cual estoy pasando la pk. Creo que no es necesario pasar el pk del seguidor (el mio en este caso) porque se asocia automáticamente con el usuario que realiza la llamada (que habrá sido previamente logueado)

2019-09-12 09:47 UTC, Vegekku commented on main/urls.py
> +    path('{0}/users/<int:pk>/unfollow'.format(api_path), view, name='user_unfollow_api'),
Mismo razonamiento que el anterior. Aunque en el excel hice las siguientes anotaciones:
podemos usar el anterior endpoint, pero con DELETE, así sabríamos que esta dejando de seguirlo. Por otra parte es más intuitivo llamar a follow o unfollow

2019-09-12 09:47 UTC, Vegekku commented on main/urls.py
> +    path('{0}/users'.format(api_path), UsersAPI.as_view(), name='users_api'),
Hablado en Telegram

2019-09-12 09:47 UTC, Vegekku commented on main/urls.py
> +    path('{0}/articles'.format(api_path), ArticlesAPI.as_view(), name='articles_api'),
Hablado en telegram

2019-09-12 09:47 UTC, Vegekku commented on main/urls.py
> +    # API
El endpoint de listado de seguidores y seguidos (que entiendo serían 2 distintos) en principio no es requerido. Es algo que podemos meter nosotros opcional.

Para obtener los subrayados de usuario, se me pasó codificarlo. En el excel lo pongo como /articles/highlights nada más, pues uso el usuario que realiza la petición para obtener sus subrayados. Veo tu endpoint más intuitivo, pero por otro lado solo el usuario puede ver sus subrayados. Aun así creo que es mejor el tuyo

2019-09-12 09:52 UTC, Ferveloper commented on main/urls.py
> +    path('{0}/articles/<int:pk>/favorite'.format(api_path), view, name='article_favorite_api'),
Ok, pero entonces el nombre del campo resulta confuso. Creao que ese campo lo llamó Pablo en su PR favorite_of, dejando claro que ahi linkabas a los users q han marcado ese seticulo como favorito. Habría q revisar modelo y endpoint para evitar conflictos

2019-09-12 09:53 UTC, Ferveloper commented on main/urls.py
> +    path('{0}/articles/<int:pk>/highlight/<int:pk>'.format(api_path), view, name='article_highlight_api'),
Cierto, no pensé en delete

2019-09-12 09:54 UTC, Ferveloper commented on main/urls.py
> +    path('{0}/users/<int:pk>/follow'.format(api_path), view, name='user_follow_api'),
Ok, entendido, tiene lógica

2019-09-12 10:07 UTC, hvctgr approved these changes

2019-09-12 10:23 UTC, Vegekku commented on main/urls.py
> +    # API
Añado tu endpoint para subrayados. El de seguidores, en principio como no es necesario, lo dejo fuera

2019-09-12 10:31 UTC, Vegekku commented on main/urls.py
> +    path('{0}/articles/<int:pk>/favorite'.format(api_path), view, name='article_favorite_api'),
No existe tal campo en los modelos (si acaso `response_to`, articulo en respuesta a otro). Yo en mi otra PR he añadido al modelo Favorite en el campo user `related_name='favorites'` para obtener los favoritos desde usuario. Podemos añadir al campo article `related_name='favorite_of'` para obtener todos los usuarios que han añadido el artículo como favorito
Esto habrá que dejarlo a elección de quien desarrolle este endpoint

2019-09-12 10:45 UTC, merged