Feature/pri article api post delete
TheDevengers/welldone-BE pull request #20
Opened 2019-09-25 18:01 UTC by Vegekku

* Añadida varible de entorno para modificar la duración de ACCESS_TOKEN.
* Adaptación a las vistas de API genéricas.
* Modificación en la creación de slug: solo funciona cuando se crea un artículo. Si se edita ha de indicarse expresamente el nuevo slug.
* Serializador de actualización de artículo:
    * Si algún valor no es indicado, dejará los valores previos.
    * Si se indica una categoría inexistente, no se tendrá en cuenta.
* Refactorización de la paginación a un único lugar. Ha de ser incluido cuando quiera usarse, y cargarse sus propios estilos css.

2019-09-25 18:14 UTC, SabrinaFZ approved these changes

2019-09-25 19:58 UTC, Ferveloper requested changes

2019-09-25 19:58 UTC, Ferveloper commented on articles/templates/articles/list.html
> +    {% include 'pagination.html' with list=article_list params=shown_param %}
Este bloque `include`para `list.html` debe pasar también el parámetro `search` para la búsqueda de artículos.
Esta refactorización de la paginación la has hecho en base a una versión de `list.html` que no incluye las modificaciones que he hecho yo en mi PR de `search_articles` y ya están mergeadas. Es decir, en `develop` se han añadido modificaciones al HTML de la sección de la paginación que estás refactorizando, y tu te estás llevando el código antiguo de la sección de paginación a un archivo nuevo, lo cual me temo git no va a poder seguir adecuadamente.
Así que en la resolución de conflictos que necesitas hacer ten esto en cuenta, porque si no me temo que los cambios de mi rama se van a perder con esa refactorización, ya que no creo que git sepa entender bien esas modificaciones al implicar creación de nuevo archivo aparte.

2019-09-26 08:20 UTC, Vegekku commented on articles/templates/articles/list.html
> +    {% include 'pagination.html' with list=article_list params=shown_param %}
Si, lo tengo en mente para añadir tus modificaciones

2019-09-27 05:59 UTC, SabrinaFZ approved these changes

2019-09-27 09:39 UTC, merged