Feature/pub article list
TheDevengers/welldone-BE pull request #3
Opened 2019-09-11 10:48 UTC by Vegekku

He retocado algunos modelos que no pertenecen a la historia de usuario, pero que creo puede estar bien.
Respecto a la historia de usuario en si misma. Aún estoy trabajando en el diseño y estructura HTML, pero como son cosas que pueden compartirse con otras, he decidido hacer la pull request para ir sincronizando.

2019-09-11 20:36 UTC, Ferveloper requested changes

2019-09-11 20:36 UTC, Ferveloper commented on articles/models/article.py
> +    publication_date = models.DateTimeField(verbose_name='Publication date', default=datetime.now)
En la línea original de publication_date se incluye el parámetro null=True, que creo que debería conservarse, ya que necesitamos que los artículos no tengan fecha de publicación asignada para poder considerarlos borradores.

2019-09-11 21:21 UTC, SabrinaFZ commented on articles/models/article.py
> +    publication_date = models.DateTimeField(verbose_name='Publication date', default=datetime.now)
¿No faltaria el campo de video de tipor URLField en el modelo de Article?

2019-09-12 09:50 UTC, Vegekku commented on articles/models/article.py
> +    publication_date = models.DateTimeField(verbose_name='Publication date', default=datetime.now)
> En la línea original de publication_date se incluye el parámetro null=True, que creo que debería conservarse, ya que necesitamos que los artículos no tengan fecha de publicación asignada para poder considerarlos borradores.

Creo que es más correcto que por defecto (y al menos) se guarde con la fecha actual. El campo discriminatorio para considerarlos borradores es 'state', que por defecto ya es borrador

2019-09-12 09:51 UTC, Vegekku commented on articles/models/article.py
> +    publication_date = models.DateTimeField(verbose_name='Publication date', default=datetime.now)
> ¿No faltaria el campo de video de tipo URLField en el modelo de Article?

En el consenso no existe video. Yo pensé que como se indica "video o imagen destacada" por simplicidad dejamos solo la posibilidad de cargar imagen

2019-09-12 09:57 UTC, SabrinaFZ commented on articles/models/article.py
> +    publication_date = models.DateTimeField(verbose_name='Publication date', default=datetime.now)
Ah vale, sí. Entonces se deja una imagen y será de tipo Image, entonces tendría que ver como se procesaria la imagen desde Django

2019-09-12 10:02 UTC, Ferveloper commented on articles/models/article.py
> +    publication_date = models.DateTimeField(verbose_name='Publication date', default=datetime.now)
El video podríamos de momento.obviarlo, pq es rarísimo que haya artículos en internet con un video destacado en si cabecera. Mejor dejar los videos como embebibles para el cuerpo del artículo.

2019-09-12 11:08 UTC, Ferveloper approved these changes

2019-09-13 09:40 UTC, merged